import { defineConfig, type Plugin } from 'vite';
import { cpSync, createReadStream, existsSync, readFileSync, statSync } from 'node:fs';
import { dirname, extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const MANUAL_SRC = join(ROOT, 'docs', 'manual');

// App version + codename — the single source of truth is version.json at the
// repo root (bumped by tools/bump-version.mjs / the pre-push hook). Read it at
// config time and inline it into the bundle via `define` so the running app can
// show it next to the logo. Falls back to a sane default if the file is missing.
function readAppVersion(): { version: string; codename: string } {
  try {
    const v = JSON.parse(readFileSync(join(ROOT, 'version.json'), 'utf8'));
    return {
      version: typeof v.version === 'string' ? v.version : '0.0',
      codename: typeof v.codename === 'string' ? v.codename : 'Unknown',
    };
  } catch {
    return { version: '0.0', codename: 'Unknown' };
  }
}
const APP_VERSION = readAppVersion();

const MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.md': 'text/markdown; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.pdf': 'application/pdf',
};

/**
 * Ships the generated user manual (docs/manual/) with the app:
 *  - dev: serves it at /manual/* so the in-app "Manual" link works in `npm run dev`
 *  - build: copies it into dist/manual/ so it deploys with the bundle
 *    (on GitHub Pages it lands at <base>/manual/, e.g. /Loom/manual/).
 * The manual is generated by `npm run build:manual`; this only serves/copies it.
 */
function manualPlugin(): Plugin {
  return {
    name: 'loom-manual',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = req.url ?? '';
        if (url !== '/manual' && !url.startsWith('/manual/')) return next();
        let rel = decodeURIComponent(url.slice('/manual'.length).split('?')[0]);
        if (rel === '' || rel === '/') rel = '/index.html';
        const file = normalize(join(MANUAL_SRC, rel));
        if (!file.startsWith(MANUAL_SRC) || !existsSync(file) || !statSync(file).isFile()) {
          return next();
        }
        res.setHeader('Content-Type', MIME[extname(file).toLowerCase()] ?? 'application/octet-stream');
        createReadStream(file).pipe(res);
      });
    },
    closeBundle() {
      if (!existsSync(MANUAL_SRC)) return;
      cpSync(MANUAL_SRC, join(ROOT, 'dist', 'manual'), { recursive: true });
    },
  };
}

export default defineConfig({
  plugins: [manualPlugin()],
  // Keep the dev-server file watcher out of `.claude/` — git worktrees are created
  // under `.claude/worktrees/<name>/` (each with its own node_modules after a local
  // install). Without this, creating/installing a worktree dumps thousands of files
  // under the watched root and the PRIMARY dev server reloads/crashes. Worktrees are
  // isolated checkouts; the server serving one tree must ignore the others.
  server: { watch: { ignored: ['**/.claude/**'] } },
  define: {
    __APP_VERSION__: JSON.stringify(APP_VERSION.version),
    __APP_CODENAME__: JSON.stringify(APP_VERSION.codename),
  },
});
