import { defineConfig, type Plugin } from 'vite';
import { cpSync, createReadStream, existsSync, statSync } from 'node:fs';
import { dirname, extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const MANUAL_SRC = join(ROOT, 'docs', 'manual');

const MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.md': 'text/markdown; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.pdf': 'application/pdf',
};

/**
 * Ships the generated user manual (docs/manual/) with the app:
 *  - dev: serves it at /manual/* so the in-app "Manual" link works in `npm run dev`
 *  - build: copies it into dist/manual/ so it deploys with the bundle
 *    (on GitHub Pages it lands at <base>/manual/, e.g. /Loom/manual/).
 * The manual is generated by `npm run build:manual`; this only serves/copies it.
 */
function manualPlugin(): Plugin {
  return {
    name: 'loom-manual',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = req.url ?? '';
        if (url !== '/manual' && !url.startsWith('/manual/')) return next();
        let rel = decodeURIComponent(url.slice('/manual'.length).split('?')[0]);
        if (rel === '' || rel === '/') rel = '/index.html';
        const file = normalize(join(MANUAL_SRC, rel));
        if (!file.startsWith(MANUAL_SRC) || !existsSync(file) || !statSync(file).isFile()) {
          return next();
        }
        res.setHeader('Content-Type', MIME[extname(file).toLowerCase()] ?? 'application/octet-stream');
        createReadStream(file).pipe(res);
      });
    },
    closeBundle() {
      if (!existsSync(MANUAL_SRC)) return;
      cpSync(MANUAL_SRC, join(ROOT, 'dist', 'manual'), { recursive: true });
    },
  };
}

export default defineConfig({ plugins: [manualPlugin()] });
