import { describe, it, expect, vi } from 'vitest';

// `dsp.ts` calls Loom.registerRenderer at module scope — that is the whole point
// of the ABI — so the global must exist BEFORE the import graph is evaluated.
// vi.hoisted is the only hook that runs that early. Installing a two-line stub
// rather than the real host API is deliberate: it proves the DSP half of a
// plugin needs nothing from Loom but registerRenderer.
const registered = vi.hoisted(() => {
  const seen = new Map<string, unknown>();
  (globalThis as unknown as { Loom: unknown }).Loom = {
    apiVersion: 1,
    registerRenderer: (id: string, make: unknown) => { seen.set(id, make); },
  };
  return seen;
});

import { SubtractiveVoiceRenderer } from './dsp';
import reference from './reference-render.json';
import manifest from './plugin.json';
import type { NoteSpec, ParamBag } from '@loom/plugin-sdk';

const SR = 48000;
/** The note tools/gen-engine-reference.ts renders every reference from. */
const note: NoteSpec = { midi: 57, beginSec: 0, durationSec: 0.5, velocity: 0.8, accent: false, slide: false };
/** The reference keeps every 512th sample — enough to pin the shape, small
 *  enough to commit. Must match tools/gen-engine-reference.ts. */
const STRIDE = 512;

/** The generator built its bag from the ENGINE's declared defaults; the manifest
 *  is where those defaults live now, so reading them from it is what makes the
 *  parity meaningful — a default ported wrong shows up as a shape failure rather
 *  than being papered over by a hand-written bag. */
function defaultParams(): ParamBag {
  const bag: ParamBag = {};
  for (const p of manifest.components[0].params) bag[p.id] = p.default;
  return bag;
}

/** The same LCG the generator pins Math.random to. This engine's default patch
 *  neither drifts (master.drift 0) nor mixes noise (noise.level 0), so nothing
 *  random reaches the output — but UnisonStack still DRAWS randoms in its
 *  constructor, and pinning them keeps the render reproducible whatever a future
 *  default does with them. */
function seeded(): () => number {
  let s = 12345;
  return () => { s = (s * 1103515245 + 12345) & 0x7fffffff; return s / 0x7fffffff; };
}

function peakOf(xs: ArrayLike<number>): number {
  let p = 0;
  for (let i = 0; i < xs.length; i++) p = Math.max(p, Math.abs(xs[i]));
  return p;
}

describe('the Subtractive plugin renderer', () => {
  it('registers itself through the Loom global, under the engine id', () => {
    expect(registered.has('subtractive')).toBe(true);
  });

  it('still renders the frozen reference taken from the in-tree engine', () => {
    // The JSON was generated by tools/gen-engine-reference.ts from
    // src/audio-dsp/subtractive-renderer.ts before this plugin existed.
    const realRandom = Math.random;
    Math.random = seeded();
    let plug: number[];
    try {
      const r = new SubtractiveVoiceRenderer(note, defaultParams(), SR);
      const n = Math.round(0.6 * SR);
      plug = [];
      for (let i = 0; i < n; i++) {
        const s = r.renderSample(i / SR);
        if (i % STRIDE === 0) plug.push(s);
      }
    } finally {
      Math.random = realRandom;
    }
    expect(plug.length).toBe(reference.length);

    // The plugin no longer multiplies by its own engine trim — the host does
    // that now — so compare SHAPE: normalise both by their peak, and the ratio
    // between them must be one constant across the whole render.
    const peakRef = peakOf(reference);
    const peakPlug = peakOf(plug);
    expect(peakRef).toBeGreaterThan(0);
    expect(peakPlug).toBeGreaterThan(0);

    const k = peakRef / peakPlug;
    let worst = 0;
    for (let i = 0; i < reference.length; i++) {
      const d = Math.abs(reference[i] - plug[i] * k);
      if (d > worst) worst = d;
    }
    // Relative: the worst deviation must be a vanishing fraction of the peak.
    expect(worst / peakRef).toBeLessThan(1e-6);
  });
});
