import { describe, it, expect, vi } from 'vitest';

// `dsp.ts` calls Loom.registerRenderer at module scope — that is the whole point
// of the ABI — so the global must exist BEFORE the import graph is evaluated.
// vi.hoisted is the only hook that runs that early. Installing a two-line stub
// rather than the real host API is deliberate: it proves the DSP half of a
// plugin needs nothing from Loom but registerRenderer.
const registered = vi.hoisted(() => {
  const seen = new Map<string, unknown>();
  (globalThis as unknown as { Loom: unknown }).Loom = {
    apiVersion: 1,
    registerRenderer: (id: string, make: unknown) => { seen.set(id, make); },
  };
  return seen;
});

import { WavetableRenderer } from './dsp';
import reference from './reference-render.json';
import manifest from './plugin.json';
import type { NoteSpec, ParamBag } from '@loom/plugin-sdk';

const SR = 48000;
const note: NoteSpec = { midi: 57, beginSec: 0, durationSec: 0.5, velocity: 0.8, accent: false, slide: false };
/** The reference keeps every 512th sample — enough to pin the shape, small
 *  enough to commit. Must match tools/gen-engine-reference.ts. */
const STRIDE = 512;

/** The manifest's declared defaults, exactly as tools/gen-engine-reference.ts
 *  builds them (from the engine's own defaults, not a hand-written bag). So a
 *  default that drifted while porting the params into plugin.json shows up here
 *  as a parity failure instead of hiding. */
function defaultParams(): ParamBag {
  const bag: ParamBag = {};
  for (const p of manifest.components[0].params) bag[p.id] = p.default;
  return bag;
}

function peakOf(xs: ArrayLike<number>): number {
  let p = 0;
  for (let i = 0; i < xs.length; i++) p = Math.max(p, Math.abs(xs[i]));
  return p;
}

describe('the Wavetable plugin renderer', () => {
  it('registers itself through the Loom global, under the engine id', () => {
    expect(registered.has('wavetable')).toBe(true);
  });

  it('still renders the frozen reference taken from the in-tree engine', () => {
    // The JSON was generated by tools/gen-engine-reference.ts from
    // src/audio-dsp/wavetable-renderer.ts BEFORE anything was touched — a
    // reference captured afterwards would only freeze whatever the move broke.
    const r = new WavetableRenderer(note, defaultParams(), SR);
    const n = Math.round(0.6 * SR);
    const plug: number[] = [];
    for (let i = 0; i < n; i++) {
      const s = r.renderSample(i / SR);
      if (i % STRIDE === 0) plug.push(s);
    }
    expect(plug.length).toBe(reference.length);

    // The plugin no longer multiplies by its own engine trim — the host does
    // that now — so compare SHAPE: normalise both by their peak, and the ratio
    // between them must be one constant across the whole render.
    const peakRef = peakOf(reference);
    const peakPlug = peakOf(plug);
    expect(peakRef).toBeGreaterThan(0);
    expect(peakPlug).toBeGreaterThan(0);

    const k = peakRef / peakPlug;
    let worst = 0;
    for (let i = 0; i < reference.length; i++) {
      const d = Math.abs(reference[i] - plug[i] * k);
      if (d > worst) worst = d;
    }
    // Relative: the worst deviation must be a vanishing fraction of the peak.
    expect(worst / peakRef).toBeLessThan(1e-6);
  });
});
