import { describe, it, expect, vi } from 'vitest';

// `dsp.ts` calls Loom.registerRenderer at module scope — that is the whole point
// of the ABI — so the global must exist BEFORE the import graph is evaluated.
// vi.hoisted is the only hook that runs that early. Installing a two-line stub
// rather than the real host API is deliberate: it proves the DSP half of a
// plugin needs nothing from Loom but registerRenderer.
const registered = vi.hoisted(() => {
  const seen = new Map<string, unknown>();
  (globalThis as unknown as { Loom: unknown }).Loom = {
    apiVersion: 1,
    registerEngine: () => {},
    registerRenderer: (id: string, make: unknown) => { seen.set(id, make); },
  };
  return seen;
});

import { KarplusRenderer } from './dsp';
import reference from './reference-render.json';
import type { NoteSpec } from '@loom/plugin-sdk';

const SR = 48000;
const note: NoteSpec = { midi: 57, beginSec: 0, durationSec: 0.5, velocity: 0.8, accent: false, slide: false };
const params = { 'string.damping': 0.5, 'string.brightness': 0.65, 'amp.level': 0.8, 'amp.release': 0.5 };
/** The reference keeps every 512th sample — enough to pin the shape, small
 *  enough to commit. Must match tools/gen-karplus-reference.ts. */
const STRIDE = 512;

/** Deterministic excitation: the pluck is random by design, so without the same
 *  seed the reference would be meaningless. Must match the generator's. */
function seeded(): () => number {
  let s = 12345;
  return () => { s = (s * 1103515245 + 12345) & 0x7fffffff; return s / 0x7fffffff; };
}

function peakOf(xs: ArrayLike<number>): number {
  let p = 0;
  for (let i = 0; i < xs.length; i++) p = Math.max(p, Math.abs(xs[i]));
  return p;
}

describe('the Karplus plugin renderer', () => {
  it('registers itself through the Loom global, under the engine id', () => {
    expect(registered.has('karplus')).toBe(true);
  });

  it('still renders the frozen reference taken from the in-tree engine', () => {
    // The in-tree renderer this was captured from is gone; the JSON IS the
    // reference now. It was generated by tools/gen-karplus-reference.ts from
    // src/audio-dsp/karplus-renderer.ts in the commit right before its deletion.
    const r = new KarplusRenderer(note, params, SR, seeded());
    const n = Math.round(0.6 * SR);
    const plug: number[] = [];
    for (let i = 0; i < n; i++) {
      const s = r.renderSample(i / SR);
      if (i % STRIDE === 0) plug.push(s);
    }
    expect(plug.length).toBe(reference.length);

    // The plugin no longer multiplies by its own engine trim — the host does
    // that now — so compare SHAPE: normalise both by their peak, and the ratio
    // between them must be one constant across the whole render.
    const peakRef = peakOf(reference);
    const peakPlug = peakOf(plug);
    expect(peakRef).toBeGreaterThan(0);
    expect(peakPlug).toBeGreaterThan(0);

    const k = peakRef / peakPlug;
    let worst = 0;
    for (let i = 0; i < reference.length; i++) {
      const d = Math.abs(reference[i] - plug[i] * k);
      if (d > worst) worst = d;
    }
    // Relative: the worst deviation must be a vanishing fraction of the peak.
    expect(worst / peakRef).toBeLessThan(1e-6);
  });
});
