// How loud each shipped preset measured, and the level a LAYER slot is
// normalised towards.
//
// The table is DATA, generated by `npx tsx tools/measure-preset-energy.ts`,
// which renders every preset through the real VoiceManager and the real plugin
// DSP. It is not derived at runtime because measuring a patch means playing it:
// three seconds per preset, 229 presets, on the thread that draws the UI.
//
// The TARGET travels with the numbers rather than being recomputed from
// whatever the table happens to hold. Recomputing would let a plugin's presets
// move the centre of the catalogue simply by being installed, so the same rack
// would balance differently before and after an unrelated install.

export interface PresetEnergyTable {
  /** The level a slot is corrected towards — the shipped catalogue's median. */
  target: number;
  /** `"<engineId>::<presetName>"` → measured energy, both declared trims in. */
  levels: Record<string, number>;
}

let cache: PresetEnergyTable | null = null;
let inflight: Promise<PresetEnergyTable | null> | null = null;

const EMPTY: PresetEnergyTable = { target: 0, levels: {} };

const valid = (b: unknown): b is PresetEnergyTable =>
  !!b && typeof b === 'object'
  && typeof (b as PresetEnergyTable).target === 'number'
  && Number.isFinite((b as PresetEnergyTable).target)
  && !!(b as PresetEnergyTable).levels
  && typeof (b as PresetEnergyTable).levels === 'object';

/** Fetch once; idempotent. A failure is not cached — the table is an
 *  improvement, so a transient miss must be retryable rather than sticky. */
export function loadPresetEnergy(fetchFn: typeof fetch = fetch): Promise<PresetEnergyTable | null> {
  if (cache) return Promise.resolve(cache);
  if (inflight) return inflight;
  inflight = (async () => {
    try {
      const res = await fetchFn(`${import.meta.env.BASE_URL}presets/preset-energy.json`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const body = await res.json();
      if (!valid(body)) throw new Error('malformed table');
      cache = body;
      return body;
    } catch (err) {
      // Absent or broken means NO normalisation, which is the behaviour before
      // this existed. A rack that sounds like it always did is a far better
      // failure than one silently rebalanced by a half-read file.
      console.warn('[preset-energy] not applied:', err);
      return null;
    } finally {
      inflight = null;
    }
  })();
  return inflight;
}

/** The measured energy of one preset, or undefined if nobody measured it —
 *  a hand-turned slot, or a preset from a plugin that ships no numbers. */
export function presetEnergy(engineId: string, presetName: string | undefined): number | undefined {
  if (!presetName || !cache) return undefined;
  const v = cache.levels[`${engineId}::${presetName}`];
  return typeof v === 'number' && Number.isFinite(v) && v > 0 ? v : undefined;
}

/** The level slots are corrected towards; 0 when no table is loaded, which
 *  `slotNormalisation` reads as "do nothing". */
export function presetEnergyTarget(): number {
  return cache?.target ?? 0;
}

/** Tests and session-reset only. */
export function _resetPresetEnergy(table: PresetEnergyTable | null = null): void {
  cache = table;
  inflight = null;
}

export { EMPTY as EMPTY_PRESET_ENERGY };
